import map from './fileIconMap.json';

/**
 * Which icon a file or folder gets — the same rules VS Code uses with the
 * Material Icon Theme: an exact file name wins (package.json, Dockerfile…), then
 * the LONGEST matching extension (test.ts before ts, d.ts before ts), then the
 * generic file icon. Folders are matched by name (css, js, src, node_modules…).
 *
 * The SVGs live in /file-icons (generated by scripts/gen-file-icons.mjs).
 * Pure functions, so the rules are testable without a browser.
 */

const BASE = '/file-icons/';

export interface ResolvedIcon {
  /** Icon for dark backgrounds (and the default). */
  src: string;
  /** Only when the theme ships a variant that reads better on white. */
  lightSrc?: string;
  /** The icon's name, e.g. "javascript" or "folder-src". */
  name: string;
}

type Maps = {
  defaults: Record<string, string | undefined>;
  ext: Record<string, string>;
  name: Record<string, string>;
  folder: Record<string, string>;
  folderOpen: Record<string, string>;
  light: { ext: Record<string, string>; name: Record<string, string>; folder: Record<string, string>; folderOpen: Record<string, string> };
};
const M = map as unknown as Maps;

const url = (name: string) => `${BASE}${name}.svg`;
const basename = (p: string) => {
  const clean = String(p || '').replace(/[\\/]+$/, '');
  return clean.split(/[\\/]/).pop() || clean;
};

export function fileIcon(path: string): ResolvedIcon {
  const base = basename(path).toLowerCase();

  let name: string | undefined = M.name[base];
  let light: string | undefined = M.light.name[base];

  if (!name) {
    // longest extension first: "foo.test.ts" -> "test.ts", then "ts"
    const parts = base.split('.');
    for (let i = 1; i < parts.length && !name; i++) {
      const ext = parts.slice(i).join('.');
      if (M.ext[ext]) {
        name = M.ext[ext];
        light = M.light.ext[ext];
      }
    }
  }
  if (!name && base.startsWith('.env')) name = M.ext.env;
  if (!name) light = M.defaults.lightFile;
  const resolved: string = name ?? M.defaults.file!;
  return { name: resolved, src: url(resolved), ...(light ? { lightSrc: url(light) } : {}) };
}

export function folderIcon(path: string, open = false): ResolvedIcon {
  const base = basename(path).toLowerCase();
  const table = open ? M.folderOpen : M.folder;
  const lightTable = open ? M.light.folderOpen : M.light.folder;
  const known: string | undefined = table[base];
  const name: string = known ?? (open ? M.defaults.folderOpen! : M.defaults.folder!);
  const light: string | undefined = known ? lightTable[base] : open ? M.defaults.lightFolderOpen : M.defaults.lightFolder;
  return { name, src: url(name), ...(light ? { lightSrc: url(light) } : {}) };
}

/** Every icon name the lookup table can return (used by tests to prove no image is missing). */
export function allIconNames(): string[] {
  const names = new Set<string>();
  for (const v of Object.values(M.defaults)) if (v) names.add(v);
  for (const table of [M.ext, M.name, M.folder, M.folderOpen, M.light.ext, M.light.name, M.light.folder, M.light.folderOpen]) {
    for (const v of Object.values(table)) names.add(v);
  }
  return [...names].sort();
}
